name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: go mod download && go build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: main
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
