name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      contains(github.event.head_commit.message, 'build') || 
      contains(github.event.head_commit.message, 'release')

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: |
        echo "TAG_NAME=$(date -u +%Y%m%d-%H%M00)" >> $GITHUB_ENV
    
    - run: |
        date="$(date -u +%Y%m%d-%H%M00)"
        name="request-url-gjson-parse-prevent-detection-v${date}"
        echo "TAG_NAME=${date}" >> $GITHUB_ENV
        echo "NAME=${name}" >> $GITHUB_ENV
        go mod download && go build -o ${name}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.NAME }}
        generate_release_notes: true
        tag_name: ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
